package com.marjorie.scoop.auth.filter

import mu.KotlinLogging
import org.springframework.security.web.csrf.CsrfToken
import javax.servlet.Filter
import javax.servlet.FilterChain
import javax.servlet.ServletRequest
import javax.servlet.ServletResponse

private val logger = KotlinLogging.logger {}

/**
 * Used to log CSRF tokens generated by the CsrfTokenRepository. Tokens are generated when user calls
 * endpoints using HTTP GET.
 */
class CsrfTokenLoggingFilter: Filter {
    override fun doFilter(request: ServletRequest, response: ServletResponse, chain: FilterChain) {
        val token =  request.getAttribute("_csrf") as CsrfToken
        logger.info("CSRF token: ${token.token}")
        chain.doFilter(request, response)
    }
}