package com.marjorie.scoop.auth.filter

import mu.KotlinLogging
import org.springframework.security.web.csrf.CsrfToken
import org.springframework.web.filter.OncePerRequestFilter
import javax.servlet.FilterChain
import javax.servlet.http.HttpServletRequest
import javax.servlet.http.HttpServletResponse

private val kotlinLogger = KotlinLogging.logger {}

/**
 * Used to log CSRF tokens generated by the CsrfTokenRepository.
 */
class CsrfLoggingFilter: OncePerRequestFilter()  {
    override fun doFilterInternal(request: HttpServletRequest, response: HttpServletResponse, chain: FilterChain) {
        val token =  request.getAttribute("_csrf") as CsrfToken
        kotlinLogger.info("CSRF-token value is ${token.token}")
        chain.doFilter(request, response)
    }
}